<script lang="ts">
	import { onMount } from 'svelte';

	let isDark = false;

	onMount(() => {
		// Check for saved theme preference or system preference
		const savedTheme = localStorage.getItem('theme') as 'light' | 'dark' | null;
		if (savedTheme) {
			isDark = savedTheme === 'dark';
		} else {
			isDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
		}
		document.documentElement.classList.toggle('dark', isDark);
	});
</script>

<svelte:head>
	<title>Terms of Service | botchat</title>
</svelte:head>

<div class="min-h-screen bg-white dark:bg-gray-900 transition-colors">
	<!-- Header -->
	<div class="bg-gradient-to-r from-blue-600 to-blue-700 dark:from-blue-800 dark:to-blue-900 text-white px-4 py-2 shadow">
		<div class="flex items-center justify-between">
			<a href="/" class="flex items-end gap-3 hover:opacity-90 transition-opacity">
				<h1 class="text-4xl font-bold leading-none">botchat</h1>
				<p class="text-blue-100 text-xs leading-tight">many minds<br/>no memory</p>
			</a>
			<div class="flex items-center gap-4">
				<a href="/" class="text-sm hover:text-blue-100 transition-colors">← Back</a>
			</div>
		</div>
	</div>

	<!-- Content -->
	<div class="max-w-3xl mx-auto px-4 py-8">
		<article class="prose prose-gray dark:prose-invert max-w-none">
			<h1 class="text-3xl font-bold text-gray-900 dark:text-white mb-2">Terms of Service</h1>
			<p class="text-sm text-gray-500 dark:text-gray-400 mb-8">Last updated: December 28, 2025</p>

			<section class="mb-8">
				<h2 class="text-xl font-semibold text-gray-900 dark:text-white mb-3">1. Acceptance of Terms</h2>
				<p class="text-gray-600 dark:text-gray-400 mb-4">
					By accessing or using botchat ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.
				</p>
			</section>

			<section class="mb-8">
				<h2 class="text-xl font-semibold text-gray-900 dark:text-white mb-3">2. Description of Service</h2>
				<p class="text-gray-600 dark:text-gray-400 mb-4">
					botchat is a web-based interface that enables users to interact with third-party AI language models (including those from Anthropic, Google, and OpenAI). The Service acts as a facilitator between you and these AI providers.
				</p>
			</section>

			<section class="mb-8">
				<h2 class="text-xl font-semibold text-gray-900 dark:text-white mb-3">3. No Warranty — Service Provided "As Is"</h2>
				<p class="text-gray-600 dark:text-gray-400 mb-4">
					THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
				</p>
				<p class="text-gray-600 dark:text-gray-400 mb-4">
					We do not warrant that:
				</p>
				<ul class="list-disc pl-6 text-gray-600 dark:text-gray-400 mb-4 space-y-2">
					<li>The Service will be uninterrupted, secure, or error-free</li>
					<li>The results obtained from using the Service will be accurate or reliable</li>
					<li>Any AI responses will be correct, appropriate, or suitable for any purpose</li>
					<li>The Service will meet your specific requirements</li>
				</ul>
			</section>

			<section class="mb-8">
				<h2 class="text-xl font-semibold text-gray-900 dark:text-white mb-3">4. Limitation of Liability</h2>
				<p class="text-gray-600 dark:text-gray-400 mb-4">
					TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BOTCHAT, ITS OPERATORS, OR AFFILIATES BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA, USE, OR OTHER INTANGIBLE LOSSES, RESULTING FROM:
				</p>
				<ul class="list-disc pl-6 text-gray-600 dark:text-gray-400 mb-4 space-y-2">
					<li>Your use or inability to use the Service</li>
					<li>Any content or responses generated by AI models</li>
					<li>Unauthorized access to or alteration of your data</li>
					<li>Any third-party conduct on the Service</li>
				</ul>
			</section>

			<section class="mb-8">
				<h2 class="text-xl font-semibold text-gray-900 dark:text-white mb-3">5. Third-Party AI Providers</h2>
				<p class="text-gray-600 dark:text-gray-400 mb-4">
					The AI models accessible through botchat are provided by third parties (Anthropic, Google, OpenAI, and others). Your use of these models is subject to the respective terms and policies of those providers. We are not responsible for the content, accuracy, or behavior of third-party AI models.
				</p>
			</section>

			<section class="mb-8">
				<h2 class="text-xl font-semibold text-gray-900 dark:text-white mb-3">6. User Responsibilities</h2>
				<p class="text-gray-600 dark:text-gray-400 mb-4">
					You agree to:
				</p>
				<ul class="list-disc pl-6 text-gray-600 dark:text-gray-400 mb-4 space-y-2">
					<li>Use the Service in compliance with all applicable laws</li>
					<li>Not use the Service to generate harmful, illegal, or abusive content</li>
					<li>Take responsibility for any API keys you provide</li>
					<li>Not attempt to circumvent any usage limits or security measures</li>
				</ul>
			</section>

			<section class="mb-8">
				<h2 class="text-xl font-semibold text-gray-900 dark:text-white mb-3">7. Privacy</h2>
				<p class="text-gray-600 dark:text-gray-400 mb-4">
					botchat is designed with privacy in mind. Conversations and attachments are not stored on our servers. Your bot configurations and API keys are stored locally in your browser. However, messages you send are transmitted to third-party AI providers according to their respective privacy policies.
				</p>
			</section>

			<section class="mb-8">
				<h2 class="text-xl font-semibold text-gray-900 dark:text-white mb-3">8. Subscription and Payments</h2>
				<p class="text-gray-600 dark:text-gray-400 mb-4">
					Paid subscriptions are billed through Stripe. Refunds are handled on a case-by-case basis. We reserve the right to modify pricing with reasonable notice.
				</p>
			</section>

			<section class="mb-8">
				<h2 class="text-xl font-semibold text-gray-900 dark:text-white mb-3">9. Termination</h2>
				<p class="text-gray-600 dark:text-gray-400 mb-4">
					We may suspend or terminate your access to the Service at any time, for any reason, without notice. You may stop using the Service at any time.
				</p>
			</section>

			<section class="mb-8">
				<h2 class="text-xl font-semibold text-gray-900 dark:text-white mb-3">10. Changes to Terms</h2>
				<p class="text-gray-600 dark:text-gray-400 mb-4">
					We reserve the right to modify these terms at any time. Continued use of the Service after changes constitutes acceptance of the modified terms.
				</p>
			</section>

			<section class="mb-8">
				<h2 class="text-xl font-semibold text-gray-900 dark:text-white mb-3">11. Governing Law</h2>
				<p class="text-gray-600 dark:text-gray-400 mb-4">
					These terms shall be governed by and construed in accordance with the laws of Ontario, Canada, without regard to conflict of law principles.
				</p>
			</section>

			<section class="mb-8">
				<h2 class="text-xl font-semibold text-gray-900 dark:text-white mb-3">12. Contact</h2>
				<p class="text-gray-600 dark:text-gray-400 mb-4">
					For questions about these Terms of Service, please contact: <a href="mailto:leo@botchat.ca" class="text-blue-600 dark:text-blue-400 hover:underline">leo@botchat.ca</a>
				</p>
			</section>
		</article>
	</div>
</div>
